server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在位置
  type-aliases-package: com.peng.demo.pojo #配置pojo所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mapper映射文件
  
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #配置数据库连接池类型
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.1.27:3306/test
    #username: root
    #password: xwzx_Sinon123
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka #配置eureka service 服务端
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept-hystrix-8001 #修改当前服务注册到eureka中的名称
    prefer-ip-address: true #访问路径可以显示IP地址,鼠标移入,左下角显示ip
    
info: #当通过eureka点击服务链接跳到xxx:xxx/info时，显示这里的内容
  app.name: peng-microservicecloud
  compant.name: www.peng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$